### ISSUE TITLE
デザイン修正　スプラッシュ画面のイメージ画像が古い

### ISSUE THREAD

**Issue by kouki0318** [GP41revolution/flutter#13]

**Comment by yamyam10** [comment]
修正しました

**Comment by kouki0318** [comment]
![image](https://github.com/user-attachments/assets/de6a1096-bddf-47f3-adf8-80d5dcc6d836)

![image](https://github.com/user-attachments/assets/48703905-66d9-4000-89c1-3604240d1e13)

これらのイメージ画像も古いので変更してください。
